# ── App ────────────────────────────────
App_Package=br.com.confesol.ib.cresol
App_Activity=br.com.confesol.ib.cresol.MainActivity
App_Min_SDK=24

# ── Execução ────────────────────────────
Framework=WDIO 8 + Appium 2 + UiAutomator2
Node_Version=v20.15.0
Tipo_dispositivo=all
Quantidade_dispositivo=3
Data_de_execução=17/04/2026, 18:40:56

# ── Dispositivos testados ───────────────
[compact] Perfil=Nexus 5X (simulado via ADB)
[compact] Tela_dp=411x731dp
[compact] Tela_px≈1079x1919px
[compact] Densidade=420dpi
[compact] Android=14 (SDK 34)
[compact] Modelo=Redmi 22101316G
[compact] Resolucao_fisica=1080x2400px
[compact] Densidade_real=440dpi
[compact] UDID=65prswbeu4z9fuhy
[standard] Perfil=Pixel 6 (simulado via ADB)
[standard] Tela_dp=411x915dp
[standard] Tela_px≈1056x2350px
[standard] Densidade=411dpi
[standard] Android=14 (SDK 34)
[standard] Modelo=Redmi 22101316G
[standard] Resolucao_fisica=1080x2400px
[standard] Densidade_real=440dpi
[standard] UDID=65prswbeu4z9fuhy
[large] Perfil=Pixel 7 Pro (simulado via ADB)
[large] Tela_dp=412x892dp
[large] Tela_px≈1442x3122px
[large] Densidade=560dpi
[large] Android=14 (SDK 34)
[large] Modelo=Redmi 22101316G
[large] Resolucao_fisica=1080x2400px
[large] Densidade_real=440dpi
[large] UDID=65prswbeu4z9fuhy